"""
Daraz Customer-Support Operations Assistant
-------------------------------------------
Streamlit RAG chat app.

- Loads a PRE-BUILT FAISS index only. Never reads, parses or re-embeds PDFs.
- Sidebar lets the user restrict retrieval to one knowledge-base section.
- Answers generated by Groq (openai/gpt-oss-120b) from retrieved chunks only.
- API key comes from st.secrets — never rendered in an input box.
"""

import json
import os
from pathlib import Path

import streamlit as st
from groq import Groq
from langchain_community.vectorstores import FAISS
from langchain_huggingface import HuggingFaceEmbeddings

# --------------------------------------------------------------------------- #
# Config
# --------------------------------------------------------------------------- #

INDEX_DIR = Path(os.getenv("FAISS_INDEX_DIR", "faiss_index"))
GROQ_MODEL = "openai/gpt-oss-120b"
FALLBACK_EMBED_MODEL = "sentence-transformers/all-MiniLM-L6-v2"

DEPARTMENTS = {
    "All sections": None,
    "Returns": "returns",
    "Delivery": "delivery",
    "Refunds": "refunds",
    "Sellers": "sellers",
    "Payments": "payments",
    "Customer support": "customer_support",
}

SYSTEM_PROMPT = """You are the Daraz Customer-Support Operations Assistant.

You help Daraz support agents answer questions using ONLY the policy excerpts
provided in the CONTEXT block.

Rules:
- Answer strictly from the CONTEXT. Never use outside knowledge or guess.
- If the CONTEXT does not contain the answer, say so plainly and suggest which
  knowledge-base section or team the agent should check next.
- Cite the source after each claim using the format [source_file, p.N].
- Be concise and operational: short paragraphs, numbered steps for procedures,
  concrete timeframes and conditions where the policy states them.
- Never invent timeframes, fees, refund amounts, or policy exceptions.
- If policies in the CONTEXT conflict, surface the conflict instead of picking one.
"""

# --------------------------------------------------------------------------- #
# Page setup + Daraz branding
# --------------------------------------------------------------------------- #

st.set_page_config(
    page_title="Daraz Support Assistant",
    page_icon="🛍️",
    layout="wide",
    initial_sidebar_state="expanded",
)

st.markdown(
    """
    <style>
      :root {
        --daraz-orange: #F85606;
        --daraz-orange-dark: #D64800;
        --daraz-ink: #1A1A1A;
        --daraz-muted: #6B7280;
        --daraz-surface: #FFF6F2;
      }
      .block-container { padding-top: 2.2rem; max-width: 1100px; }

      .daraz-header {
        background: linear-gradient(135deg, var(--daraz-orange) 0%, #FF8A3D 100%);
        color: #fff;
        padding: 1.4rem 1.6rem;
        border-radius: 14px;
        margin-bottom: 1.4rem;
        box-shadow: 0 6px 18px rgba(248, 86, 6, 0.22);
      }
      .daraz-header h1 {
        margin: 0; font-size: 1.55rem; font-weight: 700; letter-spacing: -0.3px;
      }
      .daraz-header p {
        margin: 0.35rem 0 0; font-size: 0.93rem; opacity: 0.94;
      }
      .scope-pill {
        display: inline-block;
        background: var(--daraz-surface);
        color: var(--daraz-orange-dark);
        border: 1px solid rgba(248, 86, 6, 0.28);
        border-radius: 999px;
        padding: 0.22rem 0.8rem;
        font-size: 0.8rem;
        font-weight: 600;
        margin-bottom: 0.9rem;
      }
      /* Source cards */
.src-card {
    background: var(--daraz-surface);
    color: #1A1A1A;
    border-left: 3px solid var(--daraz-orange);
    border-radius: 6px;
    padding: 0.6rem 0.85rem;
    margin-bottom: 0.6rem;
    font-size: 0.86rem;
    line-height: 1.5;
}

.src-meta {
    color: var(--daraz-orange-dark) !important;
    font-weight: 700;
    font-size: 0.78rem;
    text-transform: uppercase;
    letter-spacing: 0.4px;
}

.src-id {
    color: #6B7280 !important;
    font-weight: 500;
    text-transform: none;
}
      .stButton > button {
        background: var(--daraz-orange); color: #fff; border: 0;
        border-radius: 8px; font-weight: 600;
      }
      .stButton > button:hover { background: var(--daraz-orange-dark); color: #fff; }
      [data-testid="stSidebar"] { background: #FAFAFA;}
      [data-testid="stSidebar"] * { color: #1A1A1A; }
      [data-testid="stSidebar"] .stCaption { color: #6B7280; }
      footer, #MainMenu { visibility: hidden; }
    </style>
    """,
    unsafe_allow_html=True,
)

st.markdown(
    """
    <div class="daraz-header">
      <h1>🛍️ Daraz Customer-Support Operations Assistant</h1>
      <p>Grounded answers from the internal policy knowledge base — returns,
         delivery, refunds, sellers, payments and support playbooks.</p>
    </div>
    """,
    unsafe_allow_html=True,
)


# --------------------------------------------------------------------------- #
# Resources (cached — loaded once per session, never rebuilt)
# --------------------------------------------------------------------------- #

@st.cache_resource(show_spinner="Loading knowledge base…")
def load_vectorstore():
    """Load the pre-built FAISS index from disk. No PDF parsing, no re-embedding."""
    if not (INDEX_DIR / "index.faiss").exists():
        raise FileNotFoundError(
            f"No FAISS index at '{INDEX_DIR.resolve()}'. "
            "Run ingest.py first and copy the faiss_index folder next to app.py."
        )

    manifest_path = INDEX_DIR / "manifest.json"
    if manifest_path.exists():
        model_name = json.loads(manifest_path.read_text()).get(
            "embedding_model", FALLBACK_EMBED_MODEL
        )
    else:
        model_name = FALLBACK_EMBED_MODEL

    embeddings = HuggingFaceEmbeddings(
        model_name=model_name,
        encode_kwargs={"normalize_embeddings": True},
    )
    store = FAISS.load_local(
        str(INDEX_DIR), embeddings, allow_dangerous_deserialization=True
    )
    return store, model_name


@st.cache_resource(show_spinner=False)
def get_groq_client():
    """Groq client built from st.secrets — key is never shown or input by the user."""
    api_key = st.secrets.get("GROQ_API_KEY") or os.getenv("GROQ_API_KEY")
    if not api_key:
        raise RuntimeError(
            "GROQ_API_KEY missing. Add it to .streamlit/secrets.toml locally, "
            "or to App settings → Secrets on Streamlit Cloud."
        )
    return Groq(api_key=api_key)


try:
    vectorstore, embed_model_name = load_vectorstore()
except FileNotFoundError as exc:
    st.error(str(exc))
    st.stop()

try:
    groq_client = get_groq_client()
except RuntimeError as exc:
    st.error(str(exc))
    st.stop()


# --------------------------------------------------------------------------- #
# Sidebar — section scope + settings
# --------------------------------------------------------------------------- #

with st.sidebar:
    st.markdown("### 📚 Knowledge base")
    st.caption("Restrict the search to a single section, or leave it on all.")

    section_label = st.radio(
        "Section",
        list(DEPARTMENTS.keys()),
        index=0,
        label_visibility="collapsed",
    )
    department = DEPARTMENTS[section_label]

    st.divider()
    st.markdown("### ⚙️ Retrieval")
    top_k = st.slider("Chunks to retrieve", 2, 10, 4)
    show_sources = st.toggle("Show source excerpts", value=True)

    st.divider()
    with st.expander("Index details"):
        manifest_path = INDEX_DIR / "manifest.json"
        if manifest_path.exists():
            st.json(json.loads(manifest_path.read_text()), expanded=False)
        st.caption(f"Embeddings: `{embed_model_name}`")
        st.caption(f"Generation: `{GROQ_MODEL}` via Groq")
        st.caption("Index is read-only — PDFs are never re-processed here.")

    if st.button("🗑️ Clear chat", use_container_width=True):
        st.session_state.messages = []
        st.rerun()


# --------------------------------------------------------------------------- #
# Retrieval + generation
# --------------------------------------------------------------------------- #

def retrieve(query: str, department: str | None, k: int):
    """Similarity search, optionally filtered to one department."""
    kwargs = {"k": k}
    if department:
        kwargs["filter"] = {"department": department}
    try:
        return vectorstore.similarity_search_with_score(query, **kwargs)
    except Exception:
        return vectorstore.similarity_search_with_score(query, k=k)


def build_context(hits) -> str:
    """Flatten retrieved chunks into a numbered CONTEXT block for the LLM."""
    blocks = []
    for i, (doc, _score) in enumerate(hits, start=1):
        m = doc.metadata
        blocks.append(
            f"[{i}] source_file: {m.get('source_file', 'unknown')} | "
            f"section: {m.get('department', 'unknown')} | "
            f"page: {m.get('page', '?')} | id: {m.get('id', '-')}\n"
            f"{doc.page_content.strip()}"
        )
    return "\n\n---\n\n".join(blocks)


def stream_answer(question: str, context: str, history):
    """Stream the Groq completion, grounded in the retrieved context."""
    messages = [{"role": "system", "content": SYSTEM_PROMPT}]
    for turn in history[-6:]:
        messages.append({"role": turn["role"], "content": turn["content"]})
    messages.append(
        {
            "role": "user",
            "content": (
                f"CONTEXT:\n{context}\n\n"
                f"QUESTION: {question}\n\n"
                "Answer using only the CONTEXT above, citing sources as "
                "[source_file, p.N]."
            ),
        }
    )

    stream = groq_client.chat.completions.create(
        model=GROQ_MODEL,
        messages=messages,
        temperature=0.2,
        max_tokens=1200,
        stream=True,
    )
    for chunk in stream:
        delta = chunk.choices[0].delta.content
        if delta:
            yield delta


def render_sources(hits):
    with st.expander(f"📄 {len(hits)} source excerpt(s) used", expanded=False):
        for i, (doc, score) in enumerate(hits, start=1):
            m = doc.metadata
            excerpt = doc.page_content.strip().replace("\n", " ")[:420]
            st.markdown(
                f"""<div class="src-card">
                      <span class="src-meta">[{i}] {m.get('department','?')} ·
                      {m.get('source_file','?')} · p.{m.get('page','?')}</span>
                      <span class="src-id"> · {m.get('id','-')} ·
                      distance {score:.3f}</span><br>{excerpt}…
                    </div>""",
                unsafe_allow_html=True,
            )


# --------------------------------------------------------------------------- #
# Chat
# --------------------------------------------------------------------------- #

st.markdown(
    f'<div class="scope-pill">🔎 Searching: {section_label}</div>',
    unsafe_allow_html=True,
)

if "messages" not in st.session_state:
    st.session_state.messages = []

if not st.session_state.messages:
    st.info(
        "Ask about any Daraz policy — for example: *What is the return window for "
        "electronics?*, *How long does a refund to a bank account take?*, or "
        "*What are the seller penalties for late dispatch?*"
    )

for msg in st.session_state.messages:
    with st.chat_message(msg["role"], avatar="🛍️" if msg["role"] == "assistant" else None):
        st.markdown(msg["content"])
        if msg.get("hits") and show_sources:
            render_sources(msg["hits"])

if prompt := st.chat_input("Ask a policy question…"):
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    with st.chat_message("assistant", avatar="🛍️"):
        with st.spinner("Searching the knowledge base…"):
            hits = retrieve(prompt, department, top_k)

        if not hits:
            answer = (
                f"I couldn't find anything in the **{section_label}** section for that. "
                "Try switching the sidebar to *All sections*, or rephrase the question."
            )
            st.markdown(answer)
            st.session_state.messages.append(
                {"role": "assistant", "content": answer, "hits": []}
            )
        else:
            context = build_context(hits)
            history = [
                {"role": m["role"], "content": m["content"]}
                for m in st.session_state.messages[:-1]
            ]
            try:
                answer = st.write_stream(stream_answer(prompt, context, history))
            except Exception as exc:
                answer = f"⚠️ Groq request failed: `{exc}`"
                st.markdown(answer)

            if show_sources:
                render_sources(hits)
            st.session_state.messages.append(
                {"role": "assistant", "content": answer, "hits": hits}
            )
